### ISSUE TITLE
Not quite sure what's causing the issue.

### ISSUE THREAD

**Issue by neontetra12** [peon2/fbneo-training-mode#102]
I've had the same issue before but didn't reply, but trying the new scrolling inputs solution seems to not be working either. What could be the issue? I believe it could be running Windows 11 that causes the problem.

Fightcade FBNeo v0.2.97.44-52 fatal exception report (Tue Sep 27 17:45:26 2022
).

----------------------------------------------------------------------
Exception 0xC0000005 (EXCEPTION_ACCESS_VIOLATION) thrown.
EIP: 0x007D7B9B
 (attempting to write address 0x15CA1524)

----------------------------------------------------------------------

**Comment by peon2** [comment]
It's very hard to know what the problem is, fbneo was not designed with lua in mind and there are bugs like this. I can't easily/reliably fix them.

I would recommend changing this line from false to true if problems persist.
![image](https://user-images.githubusercontent.com/16403450/197874907-db11fa34-790c-4212-873f-dfdf62a386e9.png)
It's the very first line of the fbneo-training-mode.lua file, you can open this with notepad or notepad++ or any other text editor you like.
